# Generated by Django 5.0.4 on 2024-05-06 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("files", models.FileField(upload_to="files")),
                ("access_anyone", models.BooleanField(default=False)),
                (
                    "access_type",
                    models.CharField(
                        blank=True,
                        choices=[("viewer", "viewer"), ("editor", "editor")],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "access_user",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
