# Generated by Django 5.0.4 on 2024-05-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_documentmodel_file_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentmodel",
            name="file_type",
            field=models.CharField(
                blank=True,
                choices=[("viewer", "viewer"), ("editor", "editor")],
                max_length=25,
                null=True,
            ),
        ),
    ]
