# Generated by Django 5.0.4 on 2024-05-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_documentmodel_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentmodel",
            name="file_type",
            field=models.CharField(
                blank=True,
                choices=[("pdf", "pdf"), ("doc", "doc")],
                max_length=25,
                null=True,
            ),
        ),
    ]
