# Generated by Django 5.0.4 on 2024-05-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_documentmodel_file_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documentmodel",
            old_name="file_type",
            new_name="file_extension",
        ),
    ]
