# Generated by Django 5.0.4 on 2024-05-06 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_rename_file_type_documentmodel_file_extension"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentmodel",
            name="file_extension",
        ),
    ]
